#!/usr/bin/env python3
"""
Generate the preview pages.

The chrome (unofficial ribbon, brand bar, the pool's nav, the sub-nav across these
previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "finder":  "94hllfke9HUuzUaHoB2ZZH",   # the pool, one day, a row per part of the pool; Teams menu
    "week":    "R07JQHtJ4XjdAAarm8ofK7",   # everything, the whole week; Teams menu
    "lap":     "SupzWBAnEkR2SZcZ16sDpL",   # lap swim
    "lessons": "1MbB9BQQR4z5zvvAvSFLvW",   # lessons; Practice Groups menu picks a level
    "rec":     "SsfGHB7nk1aV8w8DRqQoYf",   # rec swim and water exercise
    "polo":    "FeqLr6dg7dmWVv650PO6tv",   # youth water polo team, Masters Family water polo
}

NAV = [
    ("index.html",           "Find a swim time"),
    ("week.html",            "The pool week"),
    ("lap-swim.html",        "Lap Swim"),
    ("swim-lessons.html",    "Swim Lessons"),
    ("rec-swim.html",        "Rec Swim &amp; Water Exercise"),
    ("water-polo.html",      "Water Polo"),
]

SITE = "https://castaic.lacountypools.com"
ACTIVENET = "https://anc.apm.activecommunities.com/losangelescounty/activity/search?onlineSiteId=0&amp;activity_select_param=2&amp;center_ids=263&amp;viewMode=list"


def cal(key, title, cls="", caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="cal {cls}">
    <iframe width="100%" height="640" src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a Los Angeles County website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a Los Angeles County page. A mockup of
  <a href="{SITE}/" target="_blank" rel="noopener">castaic.lacountypools.com</a> with live
  <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap">
    <div class="inner">
      <a class="mark" href="index.html">Castaic Aquatic Center<span class="city">SWIM | PLAY | COMPETE</span></a>
      <div class="tel">31350 Castaic Rd, Castaic &middot; 661-294-6467</div>
    </div>
  </div>
</header>

<nav class="main">
  <ul>
    <li class="on"><a href="index.html">Home</a></li>
    <li><a href="{SITE}/lessons-fall/" target="_blank" rel="noopener">Lessons</a></li>
    <li><a href="{SITE}/sports-fall/" target="_blank" rel="noopener">Team Sports</a></li>
    <li><a href="{ACTIVENET}" target="_blank" rel="noopener">Registration</a></li>
    <li><a href="https://lacountypools.com" target="_blank" rel="noopener">More Pools</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what one live schedule for the Castaic Aquatic
    Center could look like. Not affiliated with Los Angeles County Parks and Recreation.</p>
    <p>Read on 25 September 2026 from the pool's <a href="{SITE}/" target="_blank" rel="noopener">home page</a>
    (the Fall 2026 grid), its <a href="{SITE}/lessons-fall/" target="_blank" rel="noopener">Lessons</a> and
    <a href="{SITE}/sports-fall/" target="_blank" rel="noopener">Team Sports</a> pages, and
    <a href="{ACTIVENET}" target="_blank" rel="noopener">ActiveNet registration</a>. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics staff</h2>
  <p>Everything on these calendars comes from what the pool publishes. These are the places where two of
  its pages disagree, where a time isn't published, or where we had to make a call.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag gap">Gap</span>How many lanes are left for laps at 5pm?</div>
      <div class="a">From 4 to 8pm on weekdays the Fall grid shows lap swim. In the same hours the pool also
      runs a swim lesson every hour, the Youth Water Polo Team from 5 to 6, and Water Exercise from 6 to 7.
      No page says how the pool is divided.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>The Lessons page is a session behind</div>
      <div class="a">The class list on the Lessons page is Session 1 (August 24 &ndash; September 4). The
      current classes, Session 3 (September 21 &ndash; October 2), are only on ActiveNet, and they add a 7pm
      Level 3 and a 6pm Level 4 that the page doesn't show.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Saturday, September 26</div>
      <div class="a">ActiveNet lists Masters Family Water Polo from 8:30 to 11am. The Fall grid has lap swim
      8&ndash;11 and Water Exercise 8&ndash;9 at the same time, and the Saturday lessons start at 9. Does the
      game take the whole pool?</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Weekdays from 11am to 3pm</div>
      <div class="a">Nothing is scheduled between morning lap swim and afternoon rec swim. Is the pool closed,
      or open for something not listed?</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Swim Team, Dive Team and Artistic Swimming</div>
      <div class="a">The Team Sports page lists the Swim Team for &ldquo;Winter 2026&rdquo; at 5&ndash;6pm, the
      same hour as water polo, and Dive Team and Artistic Swimming as TBA.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>The 50-meter pool is closed</div>
      <div class="a">On September 25 the lifeguards said the 50-meter pool (8 long-course or 20 short-course
      lanes) is out of service, and lap swim, lessons, water exercise and rec swim all run in the 10-lane
      25-yard pool. The center also has a 3-lane shallow pool and a splash pad. No page mentions the closure
      or a reopening date.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Which lanes each program uses</div>
      <div class="a">No page says, so the calendar uses our estimate for the 10-lane 25-yard pool: lap swim in
      lanes 1&ndash;6, water exercise and youth water polo in 7&ndash;8, lessons in 9&ndash;10, rec swim across
      the pool. Water polo being in this pool at all is unconfirmed. Lessons are on the calendar through Session 3 and the Saturday session; later sessions aren't
      posted yet.</div>
    </li>
  </ul>
</section>

"""


HUB = f"""<section class="wrap hero">
  <div class="crumb">Home</div>
  <h1>Find a swim time</h1>
  <p class="kicker">Fall 2026 &middot; Aug 24 &ndash; Nov 21</p>
  <p class="lead">Everything in the water on one calendar (all of it in the 25-yard pool while the 50-meter pool is closed), lane by lane: lap
  lanes, lessons, water exercise, team sports and rec swim. Pick a <strong>day</strong>, and use the
  <strong>Teams</strong> menu to show one program.</p>

{cal("finder", "Castaic Aquatic Center — the pool, one day", "short")}

  <div class="try">
    <div><b>Laps before work?</b>Lap swim opens at 6am on weekdays and 8am on Saturday. Water Exercise
    shares the pool 6&ndash;7 and 7:30&ndash;8:30.</div>
    <div><b>Laps after work?</b>4 to 8pm on weekdays, with lessons every hour, water polo 5&ndash;6 and
    Water Exercise 6&ndash;7 in the same water.</div>
    <div><b>Free swim with the kids?</b>Rec swim is free: weekdays 3&ndash;4pm, Saturdays 12:30&ndash;4pm.</div>
  </div>
</section>

<div class="trail">
  <div class="wrap">
    <h2>Three places to look</h2>
    <p class="q">&ldquo;Can I swim laps at 5 on a Tuesday?&rdquo;</p>
    <p>The home page grid says yes: lap swim 4&ndash;8pm. The Team Sports page puts the Youth Water Polo
    Team in the pool 5&ndash;6. The Lessons page lists a 5pm Level 2 class, from a session that ended three
    weeks ago; the current one is on ActiveNet. Put together, lap swim, a lesson and water polo are all in
    the water at 5.</p>
    <p class="answer">Here they're <b>side by side on one calendar</b>, so a swimmer sees what else is in
    the water before driving over. LA County runs more than fifty pool pages like this one, and each could
    show its calendar the same way.</p>
  </div>
</div>

<section class="wrap">
  <h2>By program</h2>
  <div class="cards">
    <a class="card" href="week.html"><div class="pic loc"></div><div class="body">
      <h3>The pool week</h3><p>Monday to Saturday, everything in the water.</p></div></a>
    <a class="card" href="lap-swim.html"><div class="pic lap"></div><div class="body">
      <h3>Lap Swim</h3><p>Weekday mornings and evenings, Saturday mornings.</p></div></a>
    <a class="card" href="swim-lessons.html"><div class="pic les"></div><div class="body">
      <h3>Swim Lessons</h3><p>Parent and Child through Level 4, and adults.</p></div></a>
    <a class="card" href="rec-swim.html"><div class="pic fit"></div><div class="body">
      <h3>Rec Swim &amp; Water Exercise</h3><p>Free rec swim, and Water Exercise four times a day.</p></div></a>
    <a class="card" href="water-polo.html"><div class="pic team"></div><div class="body">
      <h3>Water Polo</h3><p>The Youth Water Polo Team and Masters Family games.</p></div></a>
  </div>
</section>

{QUESTIONS}"""


WEEK = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Home</a> &raquo; The pool week</div>
  <h1>The pool week</h1>
  <p class="kicker">Closed Sundays</p>
  <p class="lead">Everything in the pool, Monday to Saturday. Use the <strong>Teams</strong> menu to show
  one program.</p>

{cal("week", "Castaic Aquatic Center — the pool week", "tall")}
</section>

<section class="wrap">
  <h2>The pool</h2>
  <div class="facts">
    <div><b>50-meter pool</b>8 long-course lanes or 20 lanes of 25 yards. Closed for now.</div>
    <div><b>25-yard pool</b>10 lanes. Lap swim, lessons, water exercise and rec swim.</div>
    <div><b>Shallow pool and splash pad</b>A 3-lane 25-yard shallow pool, and a splash pad.</div>
    <div><b>Fees</b>Lap pass $80 for 30 entries or $15 for 5. Aquacise pass $35 a month. Rec swim
    free.</div>
  </div>
</section>

"""


LAP = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Home</a> &raquo; Lap Swim</div>
  <h1>Lap Swim</h1>
  <p class="kicker">Mon&ndash;Fri 6&ndash;11am and 4&ndash;8pm &middot; Sat 8&ndash;11am</p>
  <p class="lead">Lap swim for the fall season, August 24 to November 21. The <a href="week.html">pool
  week</a> shows what shares the pool with it.</p>

{cal("lap", "Castaic Aquatic Center — lap swim", "tall")}
</section>

"""


LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Home</a> &raquo; Swim Lessons</div>
  <h1>Swim Lessons</h1>
  <p class="kicker">Two-week sessions &middot; $25</p>
  <p class="lead">Weekday classes run in two-week sessions; Saturday classes run August 29 to October 31.
  Use the <strong>Practice Groups</strong> menu to show one level. Session 4 (October 5&ndash;16) opens for
  registration October 3.</p>

{cal("lessons", "Castaic Aquatic Center — swim lessons")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The class list is from August</h2>
    <p>The Lessons page shows the Session 1 classes, which ended September 4. The classes running now are
    on ActiveNet, where Session 3 has two more evening classes than the page lists.</p>
    <p class="answer">Here, <b>the calendar is the class list</b>. When staff post a session, the same
    calendar shows it on every page.</p>
  </div>
</div>

"""


REC = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Home</a> &raquo; Rec Swim &amp; Water Exercise</div>
  <h1>Rec Swim &amp; Water Exercise</h1>
  <p class="kicker">Rec swim is free for all ages</p>
  <p class="lead">Rec swim weekdays 3&ndash;4pm and Saturdays 12:30&ndash;4pm. Water Exercise weekdays at
  6am, 7:30am and 6pm, and Saturdays at 8am. Use the <strong>Teams</strong> menu to show one.</p>

{cal("rec", "Castaic Aquatic Center — rec swim and water exercise")}
</section>

"""


POLO = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Home</a> &raquo; Water Polo</div>
  <h1>Water Polo</h1>
  <p class="kicker">Ages 7&ndash;17 &middot; $25 per team per league</p>
  <p class="lead">The Youth Water Polo Team practices weekdays 5&ndash;6pm through November 20. Swimmers
  must swim at Level 3. Masters Family Water Polo plays Saturday, September 26, 8:30&ndash;11am.</p>

{cal("polo", "Castaic Aquatic Center — water polo")}
</section>

"""


PAGES = [
    ("index.html", "Find a swim time — Castaic Aquatic Center (preview)",
     "The Castaic Aquatic Center's pool on one live calendar.", HUB),
    ("week.html", "The pool week — Castaic Aquatic Center (preview)",
     "Everything in the pool for the week.", WEEK),
    ("lap-swim.html", "Lap Swim — Castaic Aquatic Center (preview)",
     "Fall lap swim hours.", LAP),
    ("swim-lessons.html", "Swim Lessons — Castaic Aquatic Center (preview)",
     "Swim lessons by level.", LESSONS),
    ("rec-swim.html", "Rec Swim & Water Exercise — Castaic Aquatic Center (preview)",
     "Free rec swim and water exercise classes.", REC),
    ("water-polo.html", "Water Polo — Castaic Aquatic Center (preview)",
     "Youth water polo team and Masters Family water polo.", POLO),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        with open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(shell(slug, title, description, body))
        print("wrote", slug)
