#!/usr/bin/env python3
"""
Castaic Aquatic Center — redesign proposal (v2). Our own design, same links and map as the
county's site, schedules from Pool Relay. Run `python3 build.py`; commit the HTML it writes.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

EMBED = {
    "finder":  "94hllfke9HUuzUaHoB2ZZH",
    "week":    "R07JQHtJ4XjdAAarm8ofK7",
    "lessons": "1MbB9BQQR4z5zvvAvSFLvW",
    "polo":    "FeqLr6dg7dmWVv650PO6tv",
}

SITE = "https://castaic.lacountypools.com"
REGISTER = ("https://anc.apm.activecommunities.com/losangelescounty/activity/search?onlineSiteId=0"
            "&amp;days_of_week=0000000&amp;activity_select_param=2&amp;center_ids=263&amp;viewMode=list")
STORE = "https://www.swimoutlet.com/lacitypools/"
MORE = "https://lacountypools.com"
MAP = ("https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3288.5565688976503!2d-118.61871102399219!3d34.48877169455426"
       "!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c27edcbe774f2f%3A0x1fee1ec6793f1a5a!2sCastaic%20Sports%20Complex%20Aquatic%20Center"
       "!5e0!3m2!1sen!2sus!4v1698981544090!5m2!1sen!2sus")
WEATHER = "https://forecast7.com/en/34d49n118d63/castaic/?unit=us"


def cal(key, title, cls=""):
    t = EMBED[key]
    return f"""<div class="cal {cls}"><iframe src="https://www.poolrelay.com/embed/{t}" title="{title}" loading="lazy"></iframe></div>
    <p class="capt">Updated live from the pool's schedule. <a href="https://www.poolrelay.com/v/{t}" target="_blank" rel="noopener">Open it full screen</a>.</p>"""


def page(slug, title, desc, body, scripts=""):
    def nav(href, label):
        cur = ' aria-current="page"' if href == slug else ""
        return f'<a href="{href}"{cur}>{label}</a>'
    return f"""<!DOCTYPE html>
<!-- UNOFFICIAL PREVIEW. A redesign proposal, not a Los Angeles County website. Generated by build.py. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@700;800&family=Hanken+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="ribbon"><b>Unofficial preview.</b> A redesign proposal for
  <a href="{SITE}/" target="_blank" rel="noopener">castaic.lacountypools.com</a>, not a Los Angeles County page.
  Schedules by <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</div>

<header class="top">
  <div class="wrap">
    <a class="brand" href="index.html">Castaic Aquatic Center<small>Swim, play, compete</small></a>
    <nav aria-label="Main">
      {nav("index.html", "Home")}
      {nav("schedule.html", "Schedule")}
      {nav("lessons.html", "Lessons")}
      {nav("team-sports.html", "Team Sports")}
      <a href="{STORE}" target="_blank" rel="noopener">Swim Store</a>
      <a href="{MORE}" target="_blank" rel="noopener">More Pools</a>
      <a class="register" href="{REGISTER}" target="_blank" rel="noopener">Register</a>
    </nav>
  </div>
</header>

<main>
{body}
</main>

<footer>
  <div class="wrap">
    <div class="cols">
      <div>
        <h3>Castaic Aquatic Center</h3>
        31350 Castaic Rd, Castaic, CA 91384<br>
        <a href="tel:+16612946467">661-294-6467</a><br>
        Closed Sundays
      </div>
      <div>
        <h3>Swim</h3>
        <ul>
          <li><a href="schedule.html">Pool schedule</a></li>
          <li><a href="lessons.html">Swim lessons</a></li>
          <li><a href="team-sports.html">Team sports</a></li>
          <li><a href="{REGISTER}" target="_blank" rel="noopener">Register online</a></li>
        </ul>
      </div>
      <div>
        <h3>LA County Pools</h3>
        <ul>
          <li><a href="{MORE}" target="_blank" rel="noopener">Find another pool</a></li>
          <li><a href="{STORE}" target="_blank" rel="noopener">Swim store</a></li>
          <li><a href="{WEATHER}" target="_blank" rel="noopener">Castaic weather</a></li>
          <li><a href="https://hilda.lacountypools.com/" target="_blank" rel="noopener">Hilda L. Solis pool</a></li>
        </ul>
      </div>
    </div>
    <p class="fine">Unofficial preview built to show a redesign of the Castaic Aquatic Center site. Not affiliated with
    Los Angeles County Parks and Recreation. Pool photo from lacountypools.com. The original preview is
    <a href="../index.html">here</a>.</p>
  </div>
</footer>
{scripts}
</body>
</html>
"""


HOME = f"""
<section class="hero">
  <div class="pennants" aria-hidden="true"></div>
  <div class="wrap">
    <div>
      <h1>Castaic Aquatic Center</h1>
      <p class="tag">An outdoor 50-meter pool in the hills above Santa Clarita. Open Monday to Saturday.</p>
    </div>
    <div class="now" id="now" aria-live="polite">
      <h2><span class="dot" aria-hidden="true"></span>In the water now</h2>
      <p class="when">Checking the schedule&hellip;</p>
      <ul></ul>
      <p class="foot"><a href="schedule.html">See the whole week</a></p>
    </div>
  </div>
</section>

<div class="facts">
  <div class="wrap">
    <div><b>6am</b><span>Lap swim opens weekdays; 8am Saturday</span></div>
    <div><b>Free</b><span>Rec swim for all ages, weekdays 3&ndash;4pm</span></div>
    <div><b>50 m</b><span>Eight long-course lanes, twenty short-course</span></div>
    <div><b>Aug 24&ndash;Nov 21</b><span>Fall season. Closed Sundays</span></div>
  </div>
</div>

<section class="block">
  <div class="wrap">
    <div class="intro">
      <h2>Find a swim time</h2>
      <p>Every part of the pool on one calendar: lap lanes, lessons, water exercise, team sports and rec swim.
      Pick a day, or use the Teams menu to show one program.</p>
    </div>
    {cal("finder", "Castaic Aquatic Center, one day")}
  </div>
</section>

<section class="block" style="padding-top:0">
  <div class="wrap">
    <h2>Programs</h2>
    <div class="lanes">
      <a class="row" href="schedule.html">
        <h3>Lap Swim</h3>
        <div class="hrs"><b>Mon&ndash;Fri</b> 6&ndash;11am and 4&ndash;8pm. <b>Sat</b> 8&ndash;11am.<br>Lap pass $80 for 30 swims or $15 for 5.</div>
        <span class="go">See lap swim</span>
      </a>
      <a class="row" href="lessons.html">
        <h3>Swim Lessons</h3>
        <div class="hrs">Parent and Child through Level 4, and adults. Two-week weekday sessions and a Saturday session.<br>$25 a session.</div>
        <span class="go">See lessons</span>
      </a>
      <a class="row" href="schedule.html">
        <h3>Rec Swim</h3>
        <div class="hrs"><b>Mon&ndash;Fri</b> 3&ndash;4pm. <b>Sat</b> 12:30&ndash;4pm.<br>Free for all ages.</div>
        <span class="go">See rec swim</span>
      </a>
      <a class="row" href="schedule.html">
        <h3>Water Exercise</h3>
        <div class="hrs"><b>Mon&ndash;Fri</b> 6am, 7:30am and 6pm. <b>Sat</b> 8am.<br>Aquacise pass $35 a month.</div>
        <span class="go">See water exercise</span>
      </a>
      <a class="row" href="team-sports.html">
        <h3>Team Sports</h3>
        <div class="hrs">Youth water polo weekdays 5&ndash;6pm, ages 7 to 17. Swim team, dive team and artistic swimming
        dates to be announced.</div>
        <span class="go">See team sports</span>
      </a>
    </div>
  </div>
</section>

<hr class="rope">

<section class="block visit">
  <div class="wrap grid">
    <div>
      <h2>Visit</h2>
      <dl>
        <dt>Address</dt><dd>31350 Castaic Rd<br>Castaic, CA 91384</dd>
        <dt>Phone</dt><dd><a href="tel:+16612946467">661-294-6467</a></dd>
        <dt>Open</dt><dd>Monday to Saturday. Closed Sundays.</dd>
        <dt>Weather</dt><dd><a href="{WEATHER}" target="_blank" rel="noopener">Castaic forecast</a></dd>
      </dl>
    </div>
    <div class="map"><iframe src="{MAP}" title="Map to the Castaic Aquatic Center" loading="lazy"
      referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div>
  </div>
</section>
"""


SCHEDULE = f"""
<section class="pagehead"><div class="wrap">
  <h1>Pool schedule</h1>
  <p>Fall 2026, August 24 to November 21. Use the Teams menu to show one program.</p>
</div></section>
<section class="block"><div class="wrap">
  {cal("week", "Castaic Aquatic Center, the week", "tall")}
</div></section>
"""


LESSONS = f"""
<section class="pagehead"><div class="wrap">
  <h1>Swim lessons</h1>
  <p>Parent and Child through Level 4, and adults. $25 a session. No refunds.</p>
</div></section>

<section class="block"><div class="wrap">
  <div class="intro">
    <h2>This session's classes</h2>
    <p>Classes starting at the same time share one block. Use the Practice Groups menu to show one level.</p>
  </div>
  {cal("lessons", "Castaic Aquatic Center swim lessons")}
</div></section>

<section class="block" style="padding-top:0"><div class="wrap">
  <div class="intro">
    <h2>Fall sessions</h2>
    <p>Registration opens the Saturday before each session. <a href="{REGISTER}" target="_blank" rel="noopener">Register online</a>.</p>
  </div>
  <div class="scroll">
  <table class="sessions">
    <thead><tr><th>Session</th><th>Dates</th><th>Registration opens</th></tr></thead>
    <tbody>
      <tr><td>Session 1</td><td>August 24 &ndash; September 4</td><td>August 22</td></tr>
      <tr><td>Session 2</td><td>September 8 &ndash; September 18</td><td>September 5</td></tr>
      <tr class="current"><td>Session 3</td><td>September 21 &ndash; October 2</td><td>September 19</td></tr>
      <tr><td>Session 4</td><td>October 5 &ndash; October 16</td><td>October 3</td></tr>
      <tr><td>Session 5</td><td>October 19 &ndash; October 30</td><td>October 17</td></tr>
      <tr><td>Session 6</td><td>November 2 &ndash; November 13</td><td>October 31</td></tr>
      <tr><td>Session 7</td><td>November 16 &ndash; November 20</td><td>November 14</td></tr>
      <tr><td>Saturday Session 1</td><td>August 29 &ndash; October 31</td><td>August 22</td></tr>
      <tr><td>Saturday Session 2</td><td>November 7 &ndash; December 19</td><td>October 31</td></tr>
    </tbody>
  </table>
  </div>
</div></section>
"""


TEAMS = f"""
<section class="pagehead"><div class="wrap">
  <h1>Team sports</h1>
  <p>Ages 7 to 17. Swimmers must swim at Level 3 and be comfortable in the water. $25 per team per league.</p>
</div></section>

<section class="block"><div class="wrap">
  <div class="teams">
    <div><h3>Water Polo</h3><p>Fall 2026, August 24 to November 20.<br>Monday to Friday, 5&ndash;6pm.</p></div>
    <div><h3>Swim Team</h3><p>Winter season.<br>Monday to Friday, 5&ndash;6pm.</p></div>
    <div class="tba"><h3>Dive Team</h3><p>Dates and times to be announced.</p></div>
    <div class="tba"><h3>Artistic Swimming</h3><p>Dates and times to be announced.</p></div>
  </div>
</div></section>

<section class="block" style="padding-top:0"><div class="wrap">
  <div class="intro">
    <h2>Practice schedule</h2>
    <p>Water polo practice and games. <a href="{REGISTER}" target="_blank" rel="noopener">Register online</a>.</p>
  </div>
  {cal("polo", "Castaic Aquatic Center water polo")}
</div></section>
"""


PAGES = [
    ("index.html", "Castaic Aquatic Center", "An outdoor 50-meter pool in Castaic, CA: live schedule, lessons and team sports.", HOME,
     '<script src="now.js" defer></script>'),
    ("schedule.html", "Pool schedule — Castaic Aquatic Center", "The week at the Castaic Aquatic Center.", SCHEDULE, ""),
    ("lessons.html", "Swim lessons — Castaic Aquatic Center", "Swim lessons by level and session.", LESSONS, ""),
    ("team-sports.html", "Team sports — Castaic Aquatic Center", "Water polo, swim team, dive team and artistic swimming.", TEAMS, ""),
]

if __name__ == "__main__":
    for slug, title, desc, body, js in PAGES:
        with open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(page(slug, title, desc, body, js))
        print("wrote", slug)
